name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.57.0
          - 1.56.0
          - 1.55.0
          - 1.54.0
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            profile: minimal
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
